services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_NEWS_API_KEY=${VITE_NEWS_API_KEY}
      - VITE_GUARDIAN_API_KEY=${VITE_GUARDIAN_API_KEY}
      - VITE_NYTIMES_API_KEY=${VITE_NYTIMES_API_KEY}
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SITE_URL=${VITE_SITE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    env_file:
      - .env
    command: npm run dev
